config/routes.rb
Rails.application.routes.draw do
 devise_for :users
 root to: 'homes#top'
 get 'home/about' => 'homes#about'
 get 'user/index' => 'users#index'
 resources :books, only: [:new, :create, :index, :show, :destroy, :edit, :update]
 resources :users, only: [:show, :edit, :update, :index]
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length:{ maximum: 200 }

end

app/models/post_image.rb
class PostImage < ApplicationRecord

  belongs_to :user
  attachment :image 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :profile_image
  has_many :books
  validates :name, presence: true, uniqueness: true, length:{ minimum: 2, maximum: 20 }
  validates :introduction, length:{ maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
     user_path(resource)
  end

  private

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up,keys:[:name, :email])
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def new
  @book = Book.new
  end

  def create
   @book = Book.new(book_params)
   @book.user_id = current_user.id
   if @book.save
    flash[:notice] = 'You have created book successfully.'
    redirect_to book_path(@book)
   else
    @user = User.find(current_user.id)
    @books = Book.all
    render :index
   end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
     flash[:notice] = 'You have updated book successfully.'
    redirect_to book_path(@book)
    else
      render :edit
    end
  end

  def index
   @books = Book.all
   @user = User.find(current_user.id)
   @book = Book.new
  end

  def edit
   @book = Book.find(params[:id])
   if @book.user == current_user
    render "edit"
   else
    redirect_to books_path
   end
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @book_new = Book.new
  end

  def destroy
  @book = Book.find(params[:id])
  @book.destroy

  redirect_to books_path
  end

   private
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/post_images_controller.rb
class PostImagesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
     @user = User.find(params[:id])
     @book = Book.new
     @books = @user.books.all
  end

  def index
    @users = User.all
    @user = User.find(current_user.id)
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render "users/edit"
    else
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = 'You have updated user successfully.'
    redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="container">
  <div class"row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<% if @book.errors.any? %>
  <%= @book.errors.count %>error prohibited this obj from being saved:
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>
<h1>Editing Book</h1>

<%= form_with model:@book, local:true do |f| %>
  <div class="form-group">
    <label for="inputTitle">Title</label><br/>
    <%= f.text_field :title, autofocus: true, id:"inputTitle", placeholder:"Title" %> <!--  input class="form-control"レイアウト -->
  </div>
  <div class="form-group">
    <label for="inputBody">Opinion</label><br/>
  <%= f.text_field :body, autofocus: true, id:"inputBody", placeholder:"Opinion"%>
  </div>
  <%= f.submit "Update Book",class: "btn btn-sm btn-success" %>
<% end %>
<%= link_to 'Show',book_path %>
|
<%= link_to 'Back',books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
	<% if @book.errors.any? %>
  <%= @book.errors.count %>件のエラーが発生しました
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>
<div class="container px-5 px-sm-0">
 <div class="row">
  <div class="col-md-3">
<%= render 'users/list', user: @user, book: @book %>
  </div>
  <div class="col-md-8 offset-md-1">
  <h1>Books</h1>
      <table class="table table-hover table-inverse">

        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
           <% @books.each do |book| %>
          <tr>
            <td><%= link_to user_path(book.user) do %>
            <%= attachment_image_tag book.user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "50x50" %>
            <% end %></td>
            <td><%= link_to book.title,book_path(book.id) %></td>
            <td><%= book.body %></td>
          </tr>
          <% end %>
        </tbody>
        </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
 <div class="row">
  <div class="col-md-3">
  <%= render 'users/list', user: @user, book: @book_new %>
 </div>

<div class="col-md-8 offset-md-1">
<h2>Book detail</h2>
<table class="table">
  <tbody>
    <tr>
      <td>
        <%= link_to user_path(@book.user) do %>
        <%= attachment_image_tag @book.user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "50x50" %>
        <%= @book.user.name %>
        <% end %>
      </td>
      <td>
         <%= link_to @book.title, book_path(@book) %>
      </td>
      <td>
        <%= @book.body %>
      </td>
      <td>
          <% if @user == current_user %>
          <%= link_to "Edit", edit_book_path(@book),class: "btn btn-sm btn-success" %>
          <% end %>
      </td>
      <td>
         <% if @user == current_user %>
         <%= link_to "Destroy", book_path(@book), method: :delete,class: "btn btn-sm btn-danger", data: { confirm: '本当に消しますか？'} %>
         <% end %>
      </td>
    </tr>
  </tbody>
  </table>
  </div>
  </div>
</div>

app/views/homes/about.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">
      Welcome to
      <i class="fas fa-book">
        ::before
      </i>
      <strong>Bookers</strong>
      !
    </h1>
  </div>
</div>

app/views/homes/top.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
     <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
        <h1>welcome to
         <i class="fas fa-book">
         </i>
         <strong>Bookers</strong>
         !!</h1>
         <p>In
         <i class="fas fa-book">
         </i>
          <strong>Bookers</strong>
           ,
           </p>
           <p>you can share and exchange your opinions , inpressions , and emotions</p>
           <p>about various books!</p>
           <div class="btn-wrapper col-10 mx-auto">
             <div class="row">
               <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
             </div>
             <div class="row">
              <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
             </div>
           </div>
      </div>
    </div>
 </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


   <header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/"><span>Bookers</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <% if user_signed_in? %>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <li><%= link_to 'Home',user_path(current_user),class:"fas fa-home nav-link text-light" %></li><!--users/current_user.id-->
          <li><a class="fas fa-users nav-link text-light" href="/users"> Users</a></li>
          <li><a class="fas fa-book-open nav-link text-light" href="/books"> Books</a></li>
          <li><a class="fas fa-sign-out-alt nav-link text-light" rel="nofollow" data-method="delete" href="/users/sign_out"> Log out</a></li>
        </ul>
        <% else %>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <li><%= link_to 'Home',"/",class:"fas fa-home nav-link text-light" %></li>
          <li><a class="fas fa-link nav-link text-light" href="/home/about"> About</a></li>
          <li><a class="fas fa-user-plus nav-link text-light" href="/users/sign_up"> Sign up</a></li>
          <li><a class="fas fa-sign-in-alt nav-link text-light" href="/users/sign_in"> Log in</a></li>
        </ul>
        <% end %>
      </div>
      </div>
    </div>
  </nav>
</header>
    <main>
      <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: key) %>  <!--<div class="key"> value-->
      <% end %>
      <%= yield %>
    </main>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
</html>

app/views/post_images/new.html.erb
<h1>画像投稿フォーム</h1>
<%= form_with model: @post_image, local:true do |f| %>
  <h4>画像</h4>
  <%= f.attachment_field :image %>
  <%= f.submit '投稿' %>
<% end %>

app/views/users/_list.html.erb
<div>
  <h2>User info</h2>
   <%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "50x50" %>
   <table class="table">
     <tr>
       <th>name</th>
       <th><%= user.name %></th>
     </tr>
     <tr>
       <th>introduction</th>
       <th><%= user.introduction %></th>
     </tr>
   </table>
   <%= link_to edit_user_path(user), class: 'btn btn-outline-secondary btn-block' do %>
   <i class="fas fa-user-cog"></i>
   <% end %>
</div>
   <h1>New book</h1>

    <%= form_with model: book, url:'/books', local:true do |f| %>
      <h4>Title</h4>
      <%= f.text_field :title %>
      <h4>Opinion</h4>
      <%= f.text_area :body %>
      <%= f.submit 'Create Book',class: "btn btn-sm btn-success" %>
    <% end %>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <% if @user.errors.any? %>
        <%= @user.errors.count %>件のエラーが発生しました
        <% @user.errors.full_messages.each do |message| %>
          <%= message %>
        <% end %>
      <% end %>
      <%= form_with model:@user, local:true do |f| %>
            <div class="form-group">
              <label for="user_name">Name</label><br/>
              <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"name" %>
            </div>
            <div class="form-group">
              <label for="user_image">image</label><br/>
              <%= f.attachment_field :profile_image %>
            </div>
            <div class="form-group">
              <label for="user_Introduction">Introduction</label><br/>
              <%= f.text_field :introduction, autofocus: true %>
            </div>
              <%= f.submit "Update User" %>
            <% end %>
     </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
 <div class="row">
  <div class="col-md-3">
<%= render 'users/list', user: @user, book: @book %>
  </div>
  <div class="col-md-8 offset-md-1">
  <h1>Users</h1>
     <table class="table table-hover able-inverse">

        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "50x50" %></td>
            <td><%= user.name %></td>
            <td><%= link_to 'Show',user_path(user) %></td>
          </tr>
           <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<h1>新規投稿</h1>
<%= form_with model: @book, url:'/index', local:true do |f| %>
  <h4>タイトル</h4>
  <%= f.text_field :title %>
  <h4>本文</h4>
  <%= f.text_area :body %>
  <%= f.submit '投稿' %>
<% end %>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
 <div class="row">
  <div class="col-md-3">
  <%= render 'users/list', user: @user, book: @book %>
 </div>
   <div class="col-md-8 offset-md-1">
  <h1>Books</h1>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>

            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
           <% @books.each do |book| %>
          <tr>
            <td><%= link_to user_path(book.user) do %>
            <%= attachment_image_tag book.user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "50x50" %>
            <% end %></td>
            <td><%= link_to book.title,book_path(book.id) %></td>
            <td><%= book.body %></td>
          </tr>
          <% end %>
        </tbody>
        </table>
    </div>
  </div>
</div>
<!-- <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="/">
          <span>Bookers</span>
        </a>
         <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
           <span class="navbar-toggler-icon"></span>
         </button>
         <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
         <% if user_signed_in? %>
             <li>
               <%= link_to 'Home',"users#show" %>
             </li>
             <li>
               <%= link_to 'Users',"users#index" %>
             </li>
             <li>
                <%= link_to 'Books',"books#index" %>
             </li>
             <li>
               <%= link_to 'Log out', destroy_user_session_path, method: :delete  %>
             </li>

        <% else %>
           <ul class="navbar-nav ml-auto">
             <li>
               <%= link_to 'Home',"/",class: "fas fa-home nav-link nav-link text-light" %>
             </li>
             <li>
               <%= link_to 'About',"/home/about",class: "fas fa-link nav-link text-light" %>
             </li>
             <li>
               <%= link_to 'Sign up',"/users/sign_up",class: "fas fa-user-plus nav-link text-light" %>
             </li>
             <li>
               <%= link_to 'Log in',"/users/sign_in",class: "fas fa-sign-in-alt nav-link text-light" %>
             </li>
           </ul>
         <% end %>
        </div>
      </div>
    </nav>
    </header> -->